version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    ports:
    - 5432:5432
